version: "3.7"

services:
    web:
        build: .
        ports:
            - 5000:5000
        env_file:
            - ./.flaskenv
        command: gym.py
        volumes:
            - ${PWD}:/.
